name: movie_app_design
description: Following Speed Code From https://youtu.be/gPRXrOjR_Zg?si=wtrCr1we8ygjzQNp
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0-163.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true